## Random Forest Classifier With Pipeline And Hyperparameter Tuining

In [30]:
import seaborn as sns
df = sns.load_dataset('tips')

In [31]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [32]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [33]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, str): ['Lunch', 'Dinner']

In [34]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [35]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

## label encoding

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
encoder = LabelEncoder()

In [38]:
df['time'] = encoder.fit_transform(df['time'])

In [39]:
df.head()

   total_bill   tip     sex smoker  day  time  size
0       16.99  1.01  Female     No  Sun     0     2
1       10.34  1.66    Male     No  Sun     0     3
2       21.01  3.50    Male     No  Sun     0     3
3       23.68  3.31    Male     No  Sun     0     2
4       24.59  3.61  Female     No  Sun     0     4

In [40]:
df['time'].unique()

array([0, 1])

## dependent and independent features

In [41]:
X = df.drop(labels =['time'] ,axis = 1)

In [42]:
X.head()

   total_bill   tip     sex smoker  day  size
0       16.99  1.01  Female     No  Sun     2
1       10.34  1.66    Male     No  Sun     3
2       21.01  3.50    Male     No  Sun     3
3       23.68  3.31    Male     No  Sun     2
4       24.59  3.61  Female     No  Sun     4

In [43]:
y = df.time

In [44]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: time, dtype: int64

## train_test_split

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train ,X_test , y_train,y_test = train_test_split(X,y , test_size=0.20, random_state=42)

In [47]:
X_train.shape

(195, 6)

In [48]:
X_test.shape

(49, 6)

In [49]:
y_train.shape

(195,)

In [50]:
y_test.shape

(49,)

## Featuer Engineering Automation

In [51]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer ## handling missing value
from sklearn.preprocessing import StandardScaler # feature Scaling
from sklearn.preprocessing import OneHotEncoder ## categorical to numerical
from sklearn.compose import ColumnTransformer

In [52]:
categorical_cols =['sex','smoker','day']
numerical_cols =['total_bill','size']

In [53]:
num_pipeline = Pipeline(steps=[('Imputer',SimpleImputer(strategy='median')),
                                ('scaler',StandardScaler())])

In [54]:
cat_pipeline = Pipeline(steps=[('Imputer',SimpleImputer(strategy='most_frequent')),
                                ('OneHotEncoder' , OneHotEncoder())])

In [55]:
preprocessor = ColumnTransformer([('num_pipeline',num_pipeline , numerical_cols),
                 ('cat_pipeline' , cat_pipeline , categorical_cols)])

In [56]:
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['total_bill', 'size']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('OneHotEncoder',
                                                  OneHotEncoder())]),
                                 ['sex', 'smoker', 'day'])])

## Model Building Using Random Forest

In [57]:
from sklearn.ensemble import RandomForestClassifier

In [58]:
rfc = RandomForestClassifier()